DesafioDextra/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;
using DesafioDextra.Areas.HelpPage.ModelDescriptions;

namespace DesafioDextra.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            UriParameters = new Collection<ParameterDescription>();
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ParameterDescription"/> collection that describes the URI parameters for the API.
        /// </summary>
        public Collection<ParameterDescription> UriParameters { get; private set; }

        /// <summary>
        /// Gets or sets the documentation for the request.
        /// </summary>
        public string RequestDocumentation { get; set; }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the request body.
        /// </summary>
        public ModelDescription RequestModelDescription { get; set; }

        /// <summary>
        /// Gets the request body parameter descriptions.
        /// </summary>
        public IList<ParameterDescription> RequestBodyParameters
        {
            get
            {
                return GetParameterDescriptions(RequestModelDescription);
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="ModelDescription"/> that describes the resource.
        /// </summary>
        public ModelDescription ResourceDescription { get; set; }

        /// <summary>
        /// Gets the resource property descriptions.
        /// </summary>
        public IList<ParameterDescription> ResourceProperties
        {
            get
            {
                return GetParameterDescriptions(ResourceDescription);
            }
        }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }

        private static IList<ParameterDescription> GetParameterDescriptions(ModelDescription modelDescription)
        {
            ComplexTypeModelDescription complexTypeModelDescription = modelDescription as ComplexTypeModelDescription;
            if (complexTypeModelDescription != null)
            {
                return complexTypeModelDescription.Properties;
            }

            CollectionModelDescription collectionModelDescription = modelDescription as CollectionModelDescription;
            if (collectionModelDescription != null)
            {
                complexTypeModelDescription = collectionModelDescription.ElementDescription as ComplexTypeModelDescription;
                if (complexTypeModelDescription != null)
                {
                    return complexTypeModelDescription.Properties;
                }
            }

            return null;
        }
    }
}

DesafioDextra/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using DesafioDextra.Areas.HelpPage.ModelDescriptions;
using DesafioDextra.Areas.HelpPage.Models;

namespace DesafioDextra.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

DesafioDextra/Controllers/CardapioController.cs
using DesafioDextraData;
using DesafioDextraData.Model;
using DesafioDextraRegrasDeNegocios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace DesafioDextra.Controllers
{
    public class CardapioController : Controller
    {
        Cardapio cardapio = new Cardapio();
        CalculoPrecoLanche calculoPreco = new CalculoPrecoLanche();

        public ActionResult Index()
        {
            
            List<Lanche> lanches = cardapio.ObterCardapioLanches().ToList(); 
            return View(lanches);
        }

        public ActionResult CriarLanche()
        {
            List<Ingrediente> ingredientes = cardapio.ObterCardapioIngredientes();
            return View(ingredientes);
        }

       

    }
}

DesafioDextra/Controllers/PrecosController.cs
using DesafioDextraData;
using DesafioDextraRegrasDeNegocios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Results;
using System.Web.Mvc;

namespace DesafioDextra.Controllers
{
    public class PrecosController : ApiController
    {
        Cardapio cardapio = new Cardapio();
        CalculoPrecoLanche calculoPreco = new CalculoPrecoLanche();

        public IHttpActionResult Post([FromBody]List<int> ingredientesId)
        {
            var valor = calculoPreco.CalcularPrecoDoLanche(ingredientesId);
            return Json(new { preco = valor});
        }

     }
}

DesafioDextra/Views/Cardapio/CriarLanche.cshtml
@model IEnumerable<DesafioDextraData.Model.Ingrediente>
@{
    ViewBag.Title = "CriarLanche";
}

<div class="row">
    <div class="col-xs-6">
        <h2>Criar Lanche</h2>
    </div>
    @*<div class="col-xs-6">
        <div class="preco-lanche">Preço Lanche: <span id="preco"></span> </div>
    </div>*@
</div>

<div class="row">
    <div class="col-lg-4 col-xs-6">
        @foreach (var ingrediente in Model)
    {
        <div class="ingrediente">
            <p>@ingrediente.Nome - @ingrediente.Valor <button class="btn btn-default direita" data-ingredienteId="@ingrediente.IngredienteId" data-nome="@ingrediente.Nome" onclick="adicionar(this)">Adicionar</button></p>
        </div>
}

        <div class="row">
            <div class="div-comprar col-md-4">
                <button class="btn btn-primary" onclick="comprar()">Comprar</button>
            </div>
            <div class="col-md-8">
                <div class="preco-lanche">Preço Lanche: <span id="preco"></span> </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-xs-6">
        <table class="table" id="tabela-pedido">
            <thead>
                <tr>
                    <th>Ingredientes</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>





@section scripts {

    <script type="text/javascript" src="~/Scripts/criar-lanches.js">

    </script>
}

DesafioDextra/Views/Cardapio/Index.cshtml
@model IEnumerable<DesafioDextraData.Model.Lanche>

@{
    ViewBag.Title = "Index";
}

<h2>Cardapio</h2>

@foreach (var lanche in Model)
{
    <h4>@lanche.Nome</h4>
    <p>
        Ingredientes:
        @foreach (var ingrediente in lanche.Ingredientes)
        {
            if (ingrediente.Equals(lanche.Ingredientes.Last()))
            {
                <span>@ingrediente.Nome </span>
            }
            else
            {
                <span>@ingrediente.Nome, </span>
            }

        }
        <span class="preco"> Preço: </span> @lanche.Ingredientes.Sum(ingrediente => ingrediente.Valor)
        <br /><button type="button" class="btn btn-default" data-nome="@lanche.Nome" data-preco="@lanche.Ingredientes.Sum(ingrediente => ingrediente.Valor)" onclick="escolher(this)">Escolher</button>
    </p>
}


@section scripts {

    <script type="text/javascript" src="~/Scripts/lanches-prontos.js"></script>
}

DesafioDextra/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
        a broad range of clients, including browsers and mobile devices. ASP.NET Web API
        is an ideal platform for building RESTful applications on the .NET Framework.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
    </div>
</div>

DesafioDextra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Cardapio</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cardapio Restaurante", "Index", "Cardapio", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">
                    <li id="prontos">@Html.ActionLink("Lanches Prontos", "Index", "Cardapio", new { area = "" }, null)</li>
                    <li id="criar-lanche">@Html.ActionLink("Criar Lanche", "CriarLanche", "Cardapio", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Desafio Dextra</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
    <script type="text/javascript">
            this.urls = {
                calcularValor: '@Url.Action("api/Precos",null, null, Request.Url.Scheme)'
            };
        

    </script>
    


</body>
</html>